language: elixir
elixir:
  - 1.8.2
otp_release:
  - 22.3.4.22
sudo: false
notifications:
  recipients:
    - yusufdemir286634@gmail.com
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report